[package]
name = "nterm"
version = "0.1.0"
edition = "2024"

[dependencies]
portable-pty = "0.9.0"
ratatui = "0.29.0"
syntect = "5.3.0"
tokio = { version = "1.48.0", features = ["full"] }
tui-term = "0.2.0"
tui-textarea = { version = "0.7.0", features = ["search"] }
vt100 = "0.15.2"
